### ISSUE TITLE
[BUG?] Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by black-fruit** [aledipa/Free-GPT4-WEB-API#10]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by aledipa** [comment]
Hello, does this happen on the first question or after a few?
I'm asking this because microsoft limits conversations to a handful of questions if you're not logged in.

**Comment by aledipa** [comment]
I think it is due to the new Captcha integration, as it's shown in the image below.
<img width="682" alt="Screenshot 2023-08-02 alle 11 48 58" src="https://github.com/aledipa/Free-GPT4-WEB-API/assets/51910404/049465bc-64a7-482b-8faf-72c00338db5d">

**Comment by NoctuG** [comment]
> Captcha integration

It's hard to say....
For this issue , the code should use some requirements like Scrapy. In taht case, the project need to rebuild.

**Comment by aledipa** [comment]
> > Captcha integration
> 
> It's hard to say.... For this issue , the code should use some requirements like Scrapy. In taht case, the project need to rebuild.

And so I did, the API Server is now based on [GPT4Free](https://github.com/xtekky/gpt4free) and seems to work properly.
