### ISSUE TITLE
Dangerous Issue

### ISSUE THREAD

**Issue by egcash** [aledipa/Free-GPT4-WEB-API#11]
Include Installation in README.md

**Comment by egcash** [comment]
Actually Error is :
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by aledipa** [comment]
I think, at the moment, the best thing you can do is to run the server using the Cookie as a temporary workaround.

**Comment by egcash** [comment]
This error shows both with cookies and without cookies.

**Comment by Skyro1** [comment]
bing chat ai structure is changed and they remove it from cookies after some usage then no way to find capthcae even manually to solve it

**Comment by aledipa** [comment]
This issue has been fixed with [this commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/4c7153e0e992026bca685fe8cf12b6fc424ecec4).
