### ISSUE TITLE
OpenAI-compatible API

### ISSUE THREAD

**Issue by johnd0e** [aledipa/Free-GPT4-WEB-API#12]
It would allow to make use of many existing 3rd-party tools.

**Comment by aledipa** [comment]
Thank you for the suggestion, any ideas/contributions are welcome

**Comment by norrybul** [comment]
This is the best I could think of: 
https://github.com/songquanpeng/one-api

**Comment by johnd0e** [comment]
> https://github.com/songquanpeng/one-api

Seems not related to our problem.
This is closer: https://github.com/xtekky/gpt4free/tree/main/interference

**Comment by aledipa** [comment]
> > https://github.com/songquanpeng/one-api
> 
> Seems not related to our problem. This is closer: https://github.com/xtekky/gpt4free/tree/main/interference

Seems like a good option, I have done some testing and so far have not encountered any problems. I think I will base the API server on the suggested repository soon.

**Comment by aledipa** [comment]
> Here is another project (not very mature though): https://github.com/Amm1rr/WebAI-to-API

With [this commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/4c7153e0e992026bca685fe8cf12b6fc424ecec4) I replaced EdgeGPT with GPT4Free and I will soon add the chance to choose between multiple A.I. providers.

**Comment by norrybul** [comment]
> > > https://github.com/songquanpeng/one-api
> > 
> > 
> > Seems not related to our problem. This is closer: https://github.com/xtekky/gpt4free/tree/main/interference
> 
> Seems like a good option, I have done some testing and so far have not encountered any problems. I think I will base the API server on the suggested repository soon.

Thanks for taking a look on its option. I had only come across this by chance from a friend due to [free-ai-apis](https://github.com/NovaOSS/free-ai-apis) while using BetterChatGPT and chatgpt-next-web by Yidadaa. Its the same purpose as g4f's providers, yet one-api consolidates all api collection into one single api. It kind of of help, when other services drop for some reason.
I only run a lot of these apps on my potato pc for testing purposes as a hobby. Forks of g4f/xtekky are much stable to run and easy to deploy . For Bing,I use node-chatgpt-api or EdgeGPT separately (using full cookies) or on working UIs like SydneyQT. This repo also needs a UI too.
Anyway, I'll just wait for an update. Thanks again.

**Comment by aledipa** [comment]
> > > > https://github.com/songquanpeng/one-api
> > > 
> > > 
> > > Seems not related to our problem. This is closer: https://github.com/xtekky/gpt4free/tree/main/interference
> > 
> > 
> > Seems like a good option, I have done some testing and so far have not encountered any problems. I think I will base the API server on the suggested repository soon.
> 
> Thanks for taking a look on its option. I had only come across this by chance from a friend due to [free-ai-apis](https://github.com/NovaOSS/free-ai-apis) while using BetterChatGPT and chatgpt-next-web by Yidadaa. Its the same purpose as g4f's providers, yet one-api consolidates all api collection into one single api. It kind of of help, when other services drop for some reason. I only run a lot of these apps on my potato pc for testing purposes as a hobby. Forks of g4f/xtekky are much stable to run and easy to deploy . For Bing,I use node-chatgpt-api or EdgeGPT separately (using full cookies) or on working UIs like SydneyQT. This repo also needs a UI too. Anyway, I'll just wait for an update. Thanks again.

With the latest version of the repository i've implemented a working GUI

**Comment by aledipa** [comment]
> It would allow to make use of many existing 3rd-party tools.

The latest version of the repository allows you to do that
