### ISSUE TITLE
Port 5500 is in use by another program. Either identify and stop that program, or start the server with a different port.

### ISSUE THREAD

**Issue by fitzhang** [aledipa/Free-GPT4-WEB-API#19]
when i use the comment python3 FreeGPT4_Server.py --enable-gui to open the gui.    system say that :Port 5500 is in use by another program. Either identify and stop that program, or start the server with a different port.  what is the  a different port? thanks!

**Comment by fitzhang** [comment]
My program is running inside a Docker container. I need to stop the FreeGPT4_Server.py program running inside it and open the GUI.    我的程序是运行在docker 里面的 需要停止里面的那个 FreeGPT4_Server.py程序

**Comment by PirateOfTheCaribbean** [comment]
It's simple, it's really similar to the HTTP error 406: reffatela

Maybe instead of using the port 5500 you could use the door 5500 or the gate 5500

**Comment by git-malik** [comment]
> when i use the comment python3 FreeGPT4_Server.py --enable-gui to open the gui. system say that :Port 5500 is in use by another program. Either identify and stop that program, or start the server with a different port. what is the a different port? thanks!

This error means that something else is using port 5500, to change the container's port you need to modify the `docker-compose.yml` file in this way:
```version: "3.9"
services:
  api:
    image: "d0ckmg/free-gpt4-web-api:latest"
    ports:
      - "YOUR_PORT:5500"
    command: --enable-gui

```
You will need to replace "YOUR_PORT" with a number that's not 5500.

Note that this docker-compose file also enables the GUI.

Hope this helps.
