### ISSUE TITLE
No FreeGPT4_Server.py file

### ISSUE THREAD

**Issue by says112** [aledipa/Free-GPT4-WEB-API#21]
![Снимок экрана (361)](https://github.com/aledipa/Free-GPT4-WEB-API/assets/22127398/73d6be63-e9e5-4950-b9b5-bc0b7a07edbd)

**Comment by aledipa** [comment]
> ![Снимок экрана (362)](https://github.com/aledipa/Free-GPT4-WEB-API/assets/22127398/4c482f98-2f9e-44d8-b78d-24c0c4ccffce)
> 
> I launched it but it doesn't work.

Hi, just type _/?text=your query_ next to the address in order to let the server get the wanted input

**Comment by says112** [comment]
![Снимок экрана (363)](https://github.com/aledipa/Free-GPT4-WEB-API/assets/22127398/95751ae0-7542-4793-ac4a-bae82efcd9fe)

**Comment by aledipa** [comment]
Can you please upload what is the error shown in the terminal?
