### ISSUE TITLE
hello，The method is not allowed for the requested URL.

### ISSUE THREAD

**Issue by spx88** [aledipa/Free-GPT4-WEB-API#25]
hello
<img width="401" alt="1699969935485" src="https://github.com/aledipa/Free-GPT4-WEB-API/assets/47275222/b582b628-ebb1-4495-ae1a-a82be525c971">

**Comment by aledipa** [comment]
Hello, you have to type `127.0.0.1:5500/settings` instead of `127.0.0.1:5500/login`. Also make sure you've launched the script with the `--enable-gui` flag
