### ISSUE TITLE
Blank response

### ISSUE THREAD

**Issue by abomnabilox** [aledipa/Free-GPT4-WEB-API#28]
So, if you ask a medium-long question, it just responds blank—nothing. Is it because of the tokens or the length of the message? (I'm not using any cookies, btw) or sum else? I really need an answer, please.

**Comment by aledipa** [comment]
Could You provide your current configuration? 
Does the [Demo Server](https://api.freegpt4.ddns.net/?text=Hello) have the same behaviour?

**Comment by abomnabilox** [comment]
Yes, it seems like the demo server has the same behaviour for me. 

The local api also have the same. My configuration is just the basic API without cookies  and with enabled GUI. I just changed the provider from "Bing" to "ChatGptAi" (but it seems like Bing has the same problem ?)

**Comment by aledipa** [comment]
I see, can I ask You to provide me with a query that I could use to reproduce this issue?

**Comment by abomnabilox** [comment]
It's simple: just ask some medium/long questions to the API, and after a couple of responses, it will start showing full blank. Very strange. Maybe it's the  limit per minute or just the limit. I don't know. That seems strange.

**Comment by aledipa** [comment]
That's odd, I tried it myself but couldn't reproduce the problem...

**Comment by sinuso** [comment]
> Could You provide your current configuration? Does the [Demo Server](https://api.freegpt4.ddns.net/?text=Hello) have the same behaviour?


The demo server shows this error:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by git-malik** [comment]
Now with #30 the Demo Server should work.

**Comment by abomnabilox** [comment]
Any answers ? Btw I use the "chatgpt ai" model. Like, it is working for a couple of requests but then it start to show full blank :(

**Comment by abomnabilox** [comment]
Another question: Is the Open AI chat model, where we need to connect our chatgpt account _(not the chatgptai one)_, is it infinite and unlimited/free, and we are not limited by the requests daily ?

**Comment by abomnabilox** [comment]
? @aledipa

**Comment by aledipa** [comment]
> Another question, if you're using the "OpenAI chat" model (the one where you need to connect your chatgpt account) (not the ChatGPT AI model btw) is it free and unlimited? Are there no restrictions on the number of requests you can make each day? Second question, can we add a context _(the role system/system message idk how you call it)_ to the model (example "You're a ...) without precising it in the prompt ?

Sorry for the late reply, the "OpenAI chat" model should not have any kind of restrictions and thanks to [this commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/fb6dd1a505a03c96622a670c992ce7d8bda9fe13) you're now able to use the role-system messages either from the CLI flag or from the GUI interface. If you have further doubts, don't hesitate to ask, I will try to clarify as quickly as possible.
