### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wuzzooy** [aledipa/Free-GPT4-WEB-API#31]
Hello,

I can log to the page setting but i can't actually use the chat, i have an error when putting the url http://127.0.0.1:5005/?text=your%20query
I've tried to use my own bing cookie file aswell but still have an error.

![error](https://github.com/aledipa/Free-GPT4-WEB-API/assets/147096942/011cd2df-ae5d-4cfa-816e-74a3cee24fd7)

**Comment by aledipa** [comment]
Did you edit the `settings.json` configuration file manually? 
If so, just try to rename the `"provider": "bing"` field into `"provider": "Bing"` (using capital "B")

**Comment by Wuzzooy** [comment]
I didn't edit the json but i've used "bing" as argument on one of my multiple tries and i guess it saved it on the json file.
No error anymore with (B)ing as you suggested, i close the issue, sorry for the trouble, thank you.

**Comment by aledipa** [comment]
> I didn't edit the json but i've used "bing" as argument on one of my multiple tries and i guess it saved it on the json file. No error anymore with (B)ing as you suggested, i close the issue, sorry for the trouble, thank you.

Don’t worry about it; I’m glad to have solved your problem :)
