### ISSUE TITLE
Duplicate responses.

### ISSUE THREAD

**Issue by sinuso** [aledipa/Free-GPT4-WEB-API#32]
Most answers when using a language other than English, double answers appear.

```
>Hola.
Hola, este es Bing. ¿Qué quieres saber hoy? 😊 Hello, this is Bing. What do you want to know today? 😊
```

```
>Hola buenos días.
Hola, este es Bing. ¿En qué puedo ayudarte? 😊 Hello, this is Bing. How can I help you? 😊
```

**Comment by aledipa** [comment]
The issue seems to be solved
<img width="1584" alt="Screenshot" src="https://github.com/aledipa/Free-GPT4-WEB-API/assets/51910404/b9e23e67-4809-42fe-b038-ab7209e6def2">
