### ISSUE TITLE
instructions to enable webgui in docker

### ISSUE THREAD

**Issue by carefulcomputer** [aledipa/Free-GPT4-WEB-API#33]
It seems difficult to enable webgui in docker container. please update the instructions. I tired following
1) mapped /app/src/data to one of my host folders which has settings.json and a password set
2) changed docker compose to have 
```
    command: 
      - "--remove-sources"
      - "--enable-gui"
```
I can get the docker server started. However, when I go to host:port/settings, it shows a login page, but entering the password just refreshed the login page. it doesn't take to settings page.

**Comment by aledipa** [comment]
Thank you for reporting this issue, we'll keep you updated

**Comment by git-malik** [comment]
> It seems difficult to enable webgui in docker container. please update the instructions. I tired following
> 
>     1. mapped /app/src/data to one of my host folders which has settings.json and a password set
> 
>     2. changed docker compose to have
> 
> 
> ```
>     command: 
>       - "--remove-sources"
>       - "--enable-gui"
> ```
> 
> I can get the docker server started. However, when I go to host:port/settings, it shows a login page, but entering the password just refreshed the login page. it doesn't take to settings page.

When you start the script with the `--enable-gui` parameter, the program asks for a password.
Docker compose logs:
```
        FreeGPT4 Web API - A Web API for GPT-4 (Using BingAI)
        Repo: github.com/aledipa/FreeGPT4-WEB-API
        By: Alessandro Di Pasquale

        GPT4Free Credits: github.com/xtekky/gpt4free
        
Settings page password:
 > 
Confirm password:
 > 
[V] Password set.
[V] Password saved.
 * Serving Flask app 'FreeGPT4_Server'
 * Debug mode: off
...
```
You can't set the password in the JSON file, the program does it automatically.
Thanks for reporting this issue, we are now working for a solution.

**Comment by git-malik** [comment]
It is now possible to enable the webgui on docker!
