### ISSUE TITLE
allow sending system and user commands

### ISSUE THREAD

**Issue by carefulcomputer** [aledipa/Free-GPT4-WEB-API#34]
It will be awesome if you can provide an option to send 'system' and 'user prompts in the request json.

**Comment by aledipa** [comment]
The idea itself could be nice to add but it raises some serious safety concerns, this feature could led to someone remotely controlling your system just by knowing your IP address.

**Comment by carefulcomputer** [comment]
not sure I follow. how would system prompt allow a system to be controlled ? System prompt is part of text payload (like user prompt) which gets sent to LLM.

**Comment by aledipa** [comment]
You're right, I misunderstood what you said, I'll consider adding the feature in the next updates, thank You for the suggestion :)
