### ISSUE TITLE
is this repo working?

### ISSUE THREAD

**Issue by thelege2nd** [aledipa/Free-GPT4-WEB-API#40]
curl https://api.freegpt4.ddns.net/?text= hi
The Server is under maintenance, please be patient.

is this repo working or still maintained?

**Comment by aledipa** [comment]
> curl https://api.freegpt4.ddns.net/?text= hi
> 
> The Server is under maintenance, please be patient.
> 
> 
> 
> is this repo working or still maintained?

Hi, the repo is still fully working, we're just facing some issues server-side

**Comment by aledipa** [comment]
> curl https://api.freegpt4.ddns.net/?text= hi The Server is under maintenance, please be patient.
> 
> is this repo working or still maintained?

The [Demo Server](https://api.freegpt4.ddns.net/?text=Hello) is now up and running again!
