### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by thelege2nd** [aledipa/Free-GPT4-WEB-API#41]
![image](https://github.com/aledipa/Free-GPT4-WEB-API/assets/12984941/976974e0-b54c-4bf8-aecb-61aee2166d3a)
getting this error. 

running the server on http://localhost:8081/ and i can see the ''Please enter a question'' msg.

How do you send a request and receive responses?

**Comment by aledipa** [comment]
Could you please provide more details, like the terminal output?

**Comment by aledipa** [comment]
Closing soon due to inactivity
