### ISSUE TITLE
How use Proxy

### ISSUE THREAD

**Issue by vrashad** [aledipa/Free-GPT4-WEB-API#44]
Hello After a certain number of requests, Bing blocks them. How can requests be sent through a proxy?

**Comment by aledipa** [comment]
> Hello After a certain number of requests, Bing blocks them. How can requests be sent through a proxy?

Thanks to [this commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/1ce6256edce0dbb1954c840b11a73066057323f8) you can now use one or multiple proxies of any kind just by writing them in the proxies.json file as the template inside the JSON itself shows. I hope you will find it useful!
