### ISSUE TITLE
How to add proxies without gui?

### ISSUE THREAD

**Issue by Allamaris0** [aledipa/Free-GPT4-WEB-API#50]
Hello. I use `python FreeGPT4_Server.py --enable-gui --password "mysuperpassword"` to run server but i don't see gui.
![obraz_2024-05-26_180416247](https://github.com/aledipa/Free-GPT4-WEB-API/assets/51059882/2806d069-c506-4b2d-bd72-4949fe624e37)

However it's not important because I use requests to send prompts and it works. I don't how to add proxy to the server to avoid blocking.

**Comment by Allamaris0** [comment]
Ok. I see that I have to change _proxies.json_

https://github.com/aledipa/Free-GPT4-WEB-API/issues/44

**Comment by alessandroberna** [comment]
You need to add `/settings` or `/login` at the end of the url

**Comment by Allamaris0** [comment]
> You need to add `/settings` or `/login` at the end of the url in order to display the gui

🤦 Thx, but it should be written in readme... :)

**Comment by aledipa** [comment]
> > You need to add `/settings` or `/login` at the end of the url in order to display the gui
> 
> 🤦 Thx, but it should be written in readme... :)

Done! https://github.com/aledipa/Free-GPT4-WEB-API/commit/1d41b5107e31c23b750889593fd5337ae8db52e9
