### ISSUE TITLE
Error with docker compose

### ISSUE THREAD

**Issue by mysubcult** [aledipa/Free-GPT4-WEB-API#58]
![image](https://github.com/user-attachments/assets/58d9a553-933f-4c30-8a8b-b005cd3464d3)
Running with this: sudo python3 FreeGPT4_Server.py --enable-gui --port 8080

**Comment by git-malik** [comment]
This is not an issue with docker from what I see, there was an error in requirement installation.
Could you please provide the previous commands you executed?
