### ISSUE TITLE
Does this still need cookies.json ?

### ISSUE THREAD

**Issue by accforgithubtest** [aledipa/Free-GPT4-WEB-API#6]
Hello there

Given bing is now open to public, without any login needs, can this be used without cookies.json now ?
I am using the docker compose version.

Cheers

**Comment by aledipa** [comment]
Hi!

This is now possible thanks to the [latest commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/11eccd7c3d1bac22ebaa8e9f9f2b67daba834a8d)

Thank you for asking
