### ISSUE TITLE
is it working

### ISSUE THREAD

**Issue by thelege2nd** [aledipa/Free-GPT4-WEB-API#60]
Hello, is this repo still working? your demo URL isn't working.  https://api.freegpt4.ddns.net/?text=hello

**Comment by aledipa** [comment]
Yes, it is. Sometimes the demo server may be overloaded (as written at the bottom of the readme).
If you need the demo please be patient as it may get up soon, but do not rely on it.

**Comment by aledipa** [comment]
Unfortunately there's very little we can do when the demo server gets rate-limited on multiple providers all at once
